import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "Can Upgrade";
    width: 600px;
    height: 400px;
    icon: @image-url("can-logo.png");
    in-out property <int> counter: 42;
    in-out property <string> file_name: "未选择文件";
    callback request-increase-value();
    callback openfile();
    VerticalBox {
        Text {
            text: "Counter: \{root.counter}";
        }
        Text {
            text: file_name;
        }

        Button {
            text: "Increase value";
            clicked => {
                root.request-increase-value();
            }
        }
        Button {
            text: "打开文件";
            clicked => {
                root.openfile();
            }
        }
    }
}
